name: 'Clean'
description: 'Javascript github action to clean up offline self-hosted runners'
author: 'cellinacywinska && LorenzoDrudi'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
runs:
  using: 'node16'
  main: 'dist/index.js'
